### PR TITLE
Added  API for getting timetable of Flights

### PR DESCRIPTION
**Pull request by manishkumar-hub**

### CODE REVIEW

**Review by TheLearneer — CHANGES_REQUESTED** [review]
The file format is completely wrong, please refer to one of the existing file to know more. 
You can even refer to [CONTRIBUTING.md](https://github.com/TheLearneer/api-party/blob/main/CONTRIBUTING.md) to learn more about how to do it.

Also if you are here for Hacktoberfest, please make sure to comply with the requirements mentioned in #2

**Comment by manishkumar-hub** [comment]
I have updated the file as per guideline . Please review it .

**Comment by TheLearneer** [comment]
Please make sure that all the requirements mentioned in #2  are met 🙇

**Comment by manishkumar-hub** [comment]
Updated the API link , now it's working

**Pull request closed without merging**
