### PR TITLE
Added icons for Books, Currency, Foods

### PR DESCRIPTION
**Pull request by beheradibas**
Resolving #241

### CODE REVIEW

**Review by TheLearneer — CHANGES_REQUESTED** [review]
Hello @beheradibas 

Thank you for your contribution however the changes are not as we discussed in <https://github.com/TheLearneer/api-party/issues/241#issuecomment-1272461540>

**Comment by beheradibas** [comment]
Hi @TheLearneer 

I hadn't looked into the comment and thus added the earlier images, I will make a new pull request, please review the same.

For books I think the one with 2 books looks good as the image is smaller.
And for currency I will use the one you suggested.

**Comment by beheradibas** [comment]
I have added the required changes, please review and merge the branch if appropriate.

**Comment by TheLearneer** [comment]
Hi @beheradibas 

While checking <https://apiparty.vercel.app>, the icons appear to be really small. Most likely due to extra padding all the images have around them.

Can you try and remove the additional paddings?

**Comment by beheradibas** [comment]
Which image, in all three ?

**Comment by TheLearneer** [comment]
Screen Shot 2022-10-09 at 6 04 25 PM
Screen Shot 2022-10-09 at 6 05 14 PM

I was saying if we could reduce the svg viewbox to somewhat as indicated by the red squares

**Comment by beheradibas** [comment]
I didn't find a way to convert svg element in HTML to a SVG file and thus the currency image is as it is.

**Review by TheLearneer — APPROVED** [review]
Thank you for your contribution @beheradibas

**Pull request merged**
